In [3]:
#Numpy - Manejo arreglos unidimensionales - bidimensionales columnas y filas
import numpy as np

#Instalar local
#En la terminal de visual
#pip install numpy

In [1]:
#ejemplo de listas

A=[[1,2,3],[3.0,4,5],[6,7,8]]
B=[[1,2,3],[3,4,5],[6,7,8]]

for i in A:
  print(i)

print(A[1][1])
print(A[2][2])

print(A+B)

[1, 2, 3]
[3.0, 4, 5]
[6, 7, 8]
4
8
[[1, 2, 3], [3.0, 4, 5], [6, 7, 8], [1, 2, 3], [3, 4, 5], [6, 7, 8]]


In [4]:
#Crear arreglo desde una lista

arreglo_A=np.array(A)
print(arreglo_A)
arreglo_B=np.array(B)
print(arreglo_B)
arreglo_C=arreglo_A+arreglo_B
print(arreglo_C)
print(f"Tipo de dato: {type(arreglo_A)}")
print(f"Tipo de dato de los elementos: {arreglo_A.dtype}")
print(f"Tipo de dato de los elementos: {arreglo_B.dtype}")
vacio=np.array([])
print(vacio)

[[1. 2. 3.]
 [3. 4. 5.]
 [6. 7. 8.]]
[[1 2 3]
 [3 4 5]
 [6 7 8]]
[[ 2.  4.  6.]
 [ 6.  8. 10.]
 [12. 14. 16.]]
Tipo de dato: <class 'numpy.ndarray'>
Tipo de dato de los elementos: float64
Tipo de dato de los elementos: int64
[]


In [5]:
#Crear a partir de un rango

rango_A=np.arange(1,11)
print(rango_A)
rango_B=np.arange(2,11,2)
print(rango_B)
print(rango_A.dtype)
print(rango_A.shape)
print(rango_A.ndim)

[ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10]
int64
(10,)
1


In [6]:
lista=[[2,4,6],[8,10,12]]
arreglo=np.array(lista)
print(arreglo)
print(arreglo.shape)
print(arreglo.ndim)

[[ 2  4  6]
 [ 8 10 12]]
(2, 3)
2


In [7]:
#Crear arreglo con ceros

ceros=np.zeros(10)
print(ceros)
ceros=np.zeros((5,5))
print(ceros)
ceros[3][4]=100
print(ceros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0. 100.]
 [  0.   0.   0.   0.   0.]]


In [8]:
#Crear arreglos con unos

unos=np.ones((3,5))
print(unos)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [9]:
#Crear con datos aleatorios de un rango

matriz=np.linspace(2,6,30) #Del 2 al 6, genere 20 numeros
print(matriz)
print("------------------------------------------------------------------------------")
matriz=matriz.reshape(10,3)
print(matriz)

[2.         2.13793103 2.27586207 2.4137931  2.55172414 2.68965517
 2.82758621 2.96551724 3.10344828 3.24137931 3.37931034 3.51724138
 3.65517241 3.79310345 3.93103448 4.06896552 4.20689655 4.34482759
 4.48275862 4.62068966 4.75862069 4.89655172 5.03448276 5.17241379
 5.31034483 5.44827586 5.5862069  5.72413793 5.86206897 6.        ]
------------------------------------------------------------------------------
[[2.         2.13793103 2.27586207]
 [2.4137931  2.55172414 2.68965517]
 [2.82758621 2.96551724 3.10344828]
 [3.24137931 3.37931034 3.51724138]
 [3.65517241 3.79310345 3.93103448]
 [4.06896552 4.20689655 4.34482759]
 [4.48275862 4.62068966 4.75862069]
 [4.89655172 5.03448276 5.17241379]
 [5.31034483 5.44827586 5.5862069 ]
 [5.72413793 5.86206897 6.        ]]


In [10]:
#Matriz Identica

matriz_identica=np.eye(5)
matriz_identica

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
#Matriz aleatoria entre 0 y 1

aleatoria=np.random.rand(3,5)
aleatoria

array([[0.28076352, 0.70867228, 0.43716894, 0.47719719, 0.14037618],
       [0.82432308, 0.53740686, 0.51340163, 0.75081961, 0.9882087 ],
       [0.45485169, 0.94808941, 0.08104016, 0.31461226, 0.11153865]])

In [12]:
#Matriz aleatoria entre -n y n

aleatoria1=np.random.randn(4,5)
aleatoria1

array([[ 0.87788635, -0.55356749, -0.07864994,  0.62546247,  0.90619528],
       [ 0.80182405,  0.40696542,  0.25548366, -0.15344278, -0.49256426],
       [-0.10190188, -1.50263029,  1.39588388,  0.59345547, -0.69333304],
       [ 1.21214694, -0.25283465, -0.40895397,  1.3023854 ,  0.49460459]])

In [13]:
#Matriz aleatoria de numeros enteros

enteros=np.random.randint(1,101,50) #del 1 al 100, genera 50
enteros=enteros.reshape(10,5)
enteros

array([[19, 13, 40,  9, 30],
       [98, 36, 49, 30, 97],
       [49, 50,  8, 80, 79],
       [48, 14, 18, 91, 55],
       [84, 44, 56, 27, 66],
       [81, 27, 94, 62, 77],
       [54, 60, 95, 90,  8],
       [75, 37, 10, 75, 81],
       [63, 85, 75, 62, 91],
       [96, 80, 34, 84,  4]], dtype=int32)

In [14]:
#Matriz numeros aleatorios

matrizAleatoria=np.random.uniform(4,9,size=(3,3))
matrizAleatoria

array([[5.78977527, 7.86743409, 6.83472129],
       [5.20403235, 6.51406113, 7.52110134],
       [4.18969488, 6.26461969, 4.58276221]])

In [15]:
#Matriz con unico valor

ocho=np.full((5,3),8,dtype=np.float64)
ocho

array([[8., 8., 8.],
       [8., 8., 8.],
       [8., 8., 8.],
       [8., 8., 8.],
       [8., 8., 8.]])

In [16]:
#Arreglos con mas de 2 dimensiones

dimensiones=np.array([[[12,11,10],[9,4,5]],[[13,4,5],[2,0,8]]])
print(dimensiones)
print(dimensiones.ndim)
print(dimensiones[1][0][0])

[[[12 11 10]
  [ 9  4  5]]

 [[13  4  5]
  [ 2  0  8]]]
3
13


In [17]:
arreglo_operaciones=dimensiones*2
arreglo_operaciones

array([[[24, 22, 20],
        [18,  8, 10]],

       [[26,  8, 10],
        [ 4,  0, 16]]])